// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: aliases.sql

package db

import (
	"context"
	"strings"
)

const createAlias = `-- name: CreateAlias :exec
INSERT INTO aliases (name, recipient_id, created_at) VALUES (?, ?, ?)
`

type CreateAliasParams struct {
	Name        string
	RecipientID string
	CreatedAt   string
}

func (q *Queries) CreateAlias(ctx context.Context, arg CreateAliasParams) error {
	_, err := q.db.ExecContext(ctx, createAlias, arg.Name, arg.RecipientID, arg.CreatedAt)
	return err
}

const deleteAlias = `-- name: DeleteAlias :execrows
DELETE FROM aliases WHERE name = ?
`

func (q *Queries) DeleteAlias(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAlias, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getRecipientsByAliases = `-- name: GetRecipientsByAliases :many
SELECT a.name AS alias, r.id, r.username, r.display_name, r.timezone, r.channel_preference, r.created_at
FROM aliases a JOIN recipients r ON r.id = a.recipient_id
WHERE a.name IN (/*SLICE:names*/?)
`

type GetRecipientsByAliasesRow struct {
	Alias     string
	Recipient Recipient
}

func (q *Queries) GetRecipientsByAliases(ctx context.Context, names []string) ([]GetRecipientsByAliasesRow, error) {
	query := getRecipientsByAliases
	var queryParams []interface{}
	if len(names) > 0 {
		for _, v := range names {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:names*/?", strings.Repeat(",?", len(names))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:names*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecipientsByAliasesRow{}
	for rows.Next() {
		var i GetRecipientsByAliasesRow
		if err := rows.Scan(
			&i.Alias,
			&i.Recipient.ID,
			&i.Recipient.Username,
			&i.Recipient.DisplayName,
			&i.Recipient.Timezone,
			&i.Recipient.ChannelPreference,
			&i.Recipient.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAliasesForRecipient = `-- name: ListAliasesForRecipient :many
SELECT name FROM aliases WHERE recipient_id = ? ORDER BY name
`

func (q *Queries) ListAliasesForRecipient(ctx context.Context, recipientID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAliasesForRecipient, recipientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
