// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: answers.sql

package db

import (
	"context"
	"database/sql"
)

const deleteAnswersBefore = `-- name: DeleteAnswersBefore :execrows
DELETE FROM answers WHERE message_id IN (SELECT m.id FROM messages m WHERE m.created_at < ?1)
`

func (q *Queries) DeleteAnswersBefore(ctx context.Context, cutoff string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAnswersBefore, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listAnswersForMessage = `-- name: ListAnswersForMessage :many
SELECT a.message_id, a.recipient_id, r.username, a.answer, a.answered_at
FROM answers a JOIN recipients r ON r.id = a.recipient_id
WHERE a.message_id = ? ORDER BY a.answered_at, r.username
`

type ListAnswersForMessageRow struct {
	MessageID   string
	RecipientID string
	Username    string
	Answer      []byte
	AnsweredAt  string
}

func (q *Queries) ListAnswersForMessage(ctx context.Context, messageID string) ([]ListAnswersForMessageRow, error) {
	rows, err := q.db.QueryContext(ctx, listAnswersForMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAnswersForMessageRow{}
	for rows.Next() {
		var i ListAnswersForMessageRow
		if err := rows.Scan(
			&i.MessageID,
			&i.RecipientID,
			&i.Username,
			&i.Answer,
			&i.AnsweredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAnswersFetched = `-- name: MarkAnswersFetched :exec
UPDATE answers SET fetched_at = ? WHERE message_id = ? AND fetched_at IS NULL
`

type MarkAnswersFetchedParams struct {
	FetchedAt sql.NullString
	MessageID string
}

func (q *Queries) MarkAnswersFetched(ctx context.Context, arg MarkAnswersFetchedParams) error {
	_, err := q.db.ExecContext(ctx, markAnswersFetched, arg.FetchedAt, arg.MessageID)
	return err
}

const saveAnswer = `-- name: SaveAnswer :execrows
INSERT INTO answers (message_id, recipient_id, answer, answered_at) VALUES (?, ?, ?, ?)
ON CONFLICT (message_id, recipient_id) DO UPDATE SET answer = excluded.answer, answered_at = excluded.answered_at
WHERE answers.fetched_at IS NULL
`

type SaveAnswerParams struct {
	MessageID   string
	RecipientID string
	Answer      []byte
	AnsweredAt  string
}

// Inserts or replaces an answer the app hasn't fetched yet; 0 rows means it is final.
func (q *Queries) SaveAnswer(ctx context.Context, arg SaveAnswerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveAnswer,
		arg.MessageID,
		arg.RecipientID,
		arg.Answer,
		arg.AnsweredAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
