// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package db

import (
	"context"
)

const createAttachment = `-- name: CreateAttachment :exec
INSERT INTO attachments (id, message_id, content_type, bytes, size) VALUES (?, ?, ?, ?, ?)
`

type CreateAttachmentParams struct {
	ID          string
	MessageID   string
	ContentType string
	Bytes       []byte
	Size        int64
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) error {
	_, err := q.db.ExecContext(ctx, createAttachment,
		arg.ID,
		arg.MessageID,
		arg.ContentType,
		arg.Bytes,
		arg.Size,
	)
	return err
}

const listAttachmentsForMessage = `-- name: ListAttachmentsForMessage :many
SELECT id, message_id, content_type, bytes, size FROM attachments WHERE message_id = ? ORDER BY id
`

func (q *Queries) ListAttachmentsForMessage(ctx context.Context, messageID string) ([]Attachment, error) {
	rows, err := q.db.QueryContext(ctx, listAttachmentsForMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.ContentType,
			&i.Bytes,
			&i.Size,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
