// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clients.sql

package db

import (
	"context"
	"database/sql"
)

const createClient = `-- name: CreateClient :exec
INSERT INTO clients (id, name, api_key_hash, created_at) VALUES (?, ?, ?, ?)
`

type CreateClientParams struct {
	ID         string
	Name       string
	ApiKeyHash []byte
	CreatedAt  string
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) error {
	_, err := q.db.ExecContext(ctx, createClient,
		arg.ID,
		arg.Name,
		arg.ApiKeyHash,
		arg.CreatedAt,
	)
	return err
}

const getClientByKeyHash = `-- name: GetClientByKeyHash :one
SELECT id, name, api_key_hash, created_at, revoked_at FROM clients WHERE api_key_hash = ? AND revoked_at IS NULL
`

func (q *Queries) GetClientByKeyHash(ctx context.Context, apiKeyHash []byte) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClientByKeyHash, apiKeyHash)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKeyHash,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT id, name, api_key_hash, created_at, revoked_at FROM clients ORDER BY created_at, id
`

func (q *Queries) ListClients(ctx context.Context) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, listClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ApiKeyHash,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reissueClient = `-- name: ReissueClient :one
UPDATE clients SET api_key_hash = ?, revoked_at = NULL WHERE name = ? AND revoked_at IS NOT NULL RETURNING id, name, api_key_hash, created_at, revoked_at
`

type ReissueClientParams struct {
	ApiKeyHash []byte
	Name       string
}

func (q *Queries) ReissueClient(ctx context.Context, arg ReissueClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, reissueClient, arg.ApiKeyHash, arg.Name)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ApiKeyHash,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeClient = `-- name: RevokeClient :execrows
UPDATE clients SET revoked_at = ? WHERE name = ? AND revoked_at IS NULL
`

type RevokeClientParams struct {
	RevokedAt sql.NullString
	Name      string
}

func (q *Queries) RevokeClient(ctx context.Context, arg RevokeClientParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeClient, arg.RevokedAt, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
