// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package db

import (
	"context"
	"database/sql"
)

const getContact = `-- name: GetContact :one
SELECT recipient_id, channel, address, verified_at FROM contacts WHERE recipient_id = ? AND channel = ?
`

type GetContactParams struct {
	RecipientID string
	Channel     string
}

func (q *Queries) GetContact(ctx context.Context, arg GetContactParams) (Contact, error) {
	row := q.db.QueryRowContext(ctx, getContact, arg.RecipientID, arg.Channel)
	var i Contact
	err := row.Scan(
		&i.RecipientID,
		&i.Channel,
		&i.Address,
		&i.VerifiedAt,
	)
	return i, err
}

const listContactsForRecipient = `-- name: ListContactsForRecipient :many
SELECT recipient_id, channel, address, verified_at FROM contacts WHERE recipient_id = ? ORDER BY channel
`

func (q *Queries) ListContactsForRecipient(ctx context.Context, recipientID string) ([]Contact, error) {
	rows, err := q.db.QueryContext(ctx, listContactsForRecipient, recipientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contact{}
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.RecipientID,
			&i.Channel,
			&i.Address,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertContact = `-- name: UpsertContact :exec
INSERT INTO contacts (recipient_id, channel, address, verified_at) VALUES (?, ?, ?, ?)
ON CONFLICT (recipient_id, channel) DO UPDATE SET address = excluded.address, verified_at = excluded.verified_at
`

type UpsertContactParams struct {
	RecipientID string
	Channel     string
	Address     []byte
	VerifiedAt  sql.NullString
}

func (q *Queries) UpsertContact(ctx context.Context, arg UpsertContactParams) error {
	_, err := q.db.ExecContext(ctx, upsertContact,
		arg.RecipientID,
		arg.Channel,
		arg.Address,
		arg.VerifiedAt,
	)
	return err
}
