// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deliveries.sql

package db

import (
	"context"
)

const createDelivery = `-- name: CreateDelivery :exec
INSERT INTO deliveries (id, message_id, recipient_id, channel, status, attempts, next_attempt_at, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, 0, ?, ?, ?)
`

type CreateDeliveryParams struct {
	ID            string
	MessageID     string
	RecipientID   string
	Channel       string
	Status        string
	NextAttemptAt string
	CreatedAt     string
	UpdatedAt     string
}

func (q *Queries) CreateDelivery(ctx context.Context, arg CreateDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, createDelivery,
		arg.ID,
		arg.MessageID,
		arg.RecipientID,
		arg.Channel,
		arg.Status,
		arg.NextAttemptAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listDeliveriesForMessage = `-- name: ListDeliveriesForMessage :many
SELECT id, message_id, recipient_id, channel, status, attempts, next_attempt_at, provider_message_id, last_error, created_at, updated_at FROM deliveries WHERE message_id = ? ORDER BY id
`

func (q *Queries) ListDeliveriesForMessage(ctx context.Context, messageID string) ([]Delivery, error) {
	rows, err := q.db.QueryContext(ctx, listDeliveriesForMessage, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Delivery{}
	for rows.Next() {
		var i Delivery
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.RecipientID,
			&i.Channel,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.ProviderMessageID,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
