// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package db

import (
	"context"
)

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM invites WHERE recipient_id = ? AND channel = ?
`

type DeleteInviteParams struct {
	RecipientID string
	Channel     string
}

func (q *Queries) DeleteInvite(ctx context.Context, arg DeleteInviteParams) error {
	_, err := q.db.ExecContext(ctx, deleteInvite, arg.RecipientID, arg.Channel)
	return err
}

const deleteInvitesBefore = `-- name: DeleteInvitesBefore :execrows
DELETE FROM invites WHERE created_at < ?1
`

func (q *Queries) DeleteInvitesBefore(ctx context.Context, cutoff string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteInvitesBefore, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listInvites = `-- name: ListInvites :many
SELECT recipient_id, channel, handle, created_at FROM invites WHERE channel = ?1 AND created_at >= ?2 ORDER BY created_at
`

type ListInvitesParams struct {
	Channel string
	Since   string
}

func (q *Queries) ListInvites(ctx context.Context, arg ListInvitesParams) ([]Invite, error) {
	rows, err := q.db.QueryContext(ctx, listInvites, arg.Channel, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invite{}
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.RecipientID,
			&i.Channel,
			&i.Handle,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertInvite = `-- name: UpsertInvite :exec
INSERT INTO invites (recipient_id, channel, handle, created_at) VALUES (?, ?, ?, ?)
ON CONFLICT (recipient_id, channel) DO UPDATE SET handle = excluded.handle, created_at = excluded.created_at
`

type UpsertInviteParams struct {
	RecipientID string
	Channel     string
	Handle      []byte
	CreatedAt   string
}

func (q *Queries) UpsertInvite(ctx context.Context, arg UpsertInviteParams) error {
	_, err := q.db.ExecContext(ctx, upsertInvite,
		arg.RecipientID,
		arg.Channel,
		arg.Handle,
		arg.CreatedAt,
	)
	return err
}
