// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: link_tokens.sql

package db

import (
	"context"
)

const claimLinkToken = `-- name: ClaimLinkToken :one
DELETE FROM link_tokens WHERE token_hash = ?1 AND expires_at > ?2
RETURNING recipient_id, channel
`

type ClaimLinkTokenParams struct {
	TokenHash []byte
	Now       string
}

type ClaimLinkTokenRow struct {
	RecipientID string
	Channel     string
}

func (q *Queries) ClaimLinkToken(ctx context.Context, arg ClaimLinkTokenParams) (ClaimLinkTokenRow, error) {
	row := q.db.QueryRowContext(ctx, claimLinkToken, arg.TokenHash, arg.Now)
	var i ClaimLinkTokenRow
	err := row.Scan(&i.RecipientID, &i.Channel)
	return i, err
}

const createLinkToken = `-- name: CreateLinkToken :exec
INSERT INTO link_tokens (token_hash, recipient_id, channel, created_at, expires_at) VALUES (?, ?, ?, ?, ?)
`

type CreateLinkTokenParams struct {
	TokenHash   []byte
	RecipientID string
	Channel     string
	CreatedAt   string
	ExpiresAt   string
}

func (q *Queries) CreateLinkToken(ctx context.Context, arg CreateLinkTokenParams) error {
	_, err := q.db.ExecContext(ctx, createLinkToken,
		arg.TokenHash,
		arg.RecipientID,
		arg.Channel,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteLinkTokensBefore = `-- name: DeleteLinkTokensBefore :execrows
DELETE FROM link_tokens WHERE expires_at <= ?1
`

func (q *Queries) DeleteLinkTokensBefore(ctx context.Context, now string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteLinkTokensBefore, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteLinkTokensFor = `-- name: DeleteLinkTokensFor :exec
DELETE FROM link_tokens WHERE recipient_id = ? AND channel = ?
`

type DeleteLinkTokensForParams struct {
	RecipientID string
	Channel     string
}

func (q *Queries) DeleteLinkTokensFor(ctx context.Context, arg DeleteLinkTokensForParams) error {
	_, err := q.db.ExecContext(ctx, deleteLinkTokensFor, arg.RecipientID, arg.Channel)
	return err
}
