// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"
	"database/sql"
)

const createMessage = `-- name: CreateMessage :exec
INSERT INTO messages (id, client_id, urgency, title, blocks, source, idempotency_key, request_id, status, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateMessageParams struct {
	ID             string
	ClientID       string
	Urgency        string
	Title          []byte
	Blocks         []byte
	Source         sql.NullString
	IdempotencyKey sql.NullString
	RequestID      sql.NullString
	Status         string
	CreatedAt      string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.ExecContext(ctx, createMessage,
		arg.ID,
		arg.ClientID,
		arg.Urgency,
		arg.Title,
		arg.Blocks,
		arg.Source,
		arg.IdempotencyKey,
		arg.RequestID,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const getMessage = `-- name: GetMessage :one
SELECT id, client_id, urgency, title, blocks, source, idempotency_key, request_id, status, created_at, redacted_at FROM messages WHERE id = ? AND client_id = ?
`

type GetMessageParams struct {
	ID       string
	ClientID string
}

func (q *Queries) GetMessage(ctx context.Context, arg GetMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessage, arg.ID, arg.ClientID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Urgency,
		&i.Title,
		&i.Blocks,
		&i.Source,
		&i.IdempotencyKey,
		&i.RequestID,
		&i.Status,
		&i.CreatedAt,
		&i.RedactedAt,
	)
	return i, err
}

const getMessageByIdempotencyKey = `-- name: GetMessageByIdempotencyKey :one
SELECT id, client_id, urgency, title, blocks, source, idempotency_key, request_id, status, created_at, redacted_at FROM messages WHERE client_id = ? AND idempotency_key = ?
`

type GetMessageByIdempotencyKeyParams struct {
	ClientID       string
	IdempotencyKey sql.NullString
}

func (q *Queries) GetMessageByIdempotencyKey(ctx context.Context, arg GetMessageByIdempotencyKeyParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessageByIdempotencyKey, arg.ClientID, arg.IdempotencyKey)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Urgency,
		&i.Title,
		&i.Blocks,
		&i.Source,
		&i.IdempotencyKey,
		&i.RequestID,
		&i.Status,
		&i.CreatedAt,
		&i.RedactedAt,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, client_id, urgency, title, blocks, source, idempotency_key, request_id, status, created_at, redacted_at FROM messages
WHERE client_id = ?1
  AND (?2 IS NULL OR status = ?2)
  AND (?3 IS NULL OR created_at >= ?3)
  AND (?4 IS NULL OR id < ?4)
ORDER BY id DESC
LIMIT ?5
`

type ListMessagesParams struct {
	ClientID string
	Status   interface{}
	Since    interface{}
	BeforeID interface{}
	Limit    int64
}

// Newest first. IDs are ULIDs, so id order is creation order and the last id is the cursor.
func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessages,
		arg.ClientID,
		arg.Status,
		arg.Since,
		arg.BeforeID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Urgency,
			&i.Title,
			&i.Blocks,
			&i.Source,
			&i.IdempotencyKey,
			&i.RequestID,
			&i.Status,
			&i.CreatedAt,
			&i.RedactedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessageStatus = `-- name: UpdateMessageStatus :exec
UPDATE messages SET status = ? WHERE id = ?
`

type UpdateMessageStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdateMessageStatus(ctx context.Context, arg UpdateMessageStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateMessageStatus, arg.Status, arg.ID)
	return err
}
