// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Alias struct {
	Name        string
	RecipientID string
	CreatedAt   string
}

type Answer struct {
	MessageID   string
	RecipientID string
	Answer      []byte
	AnsweredAt  string
	FetchedAt   sql.NullString
}

type Attachment struct {
	ID          string
	MessageID   string
	ContentType string
	Bytes       []byte
	Size        int64
}

type Client struct {
	ID         string
	Name       string
	ApiKeyHash []byte
	CreatedAt  string
	RevokedAt  sql.NullString
}

type Contact struct {
	RecipientID string
	Channel     string
	Address     []byte
	VerifiedAt  sql.NullString
}

type Delivery struct {
	ID                string
	MessageID         string
	RecipientID       string
	Channel           string
	Status            string
	Attempts          int64
	NextAttemptAt     string
	ProviderMessageID sql.NullString
	LastError         sql.NullString
	CreatedAt         string
	UpdatedAt         string
}

type Invite struct {
	RecipientID string
	Channel     string
	Handle      []byte
	CreatedAt   string
}

type Message struct {
	ID             string
	ClientID       string
	Urgency        string
	Title          []byte
	Blocks         []byte
	Source         sql.NullString
	IdempotencyKey sql.NullString
	RequestID      sql.NullString
	Status         string
	CreatedAt      string
	RedactedAt     sql.NullString
}

type Recipient struct {
	ID                string
	Username          string
	DisplayName       string
	Timezone          string
	ChannelPreference string
	CreatedAt         string
}
