// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipients.sql

package db

import (
	"context"
	"strings"
)

const createRecipient = `-- name: CreateRecipient :exec
INSERT INTO recipients (id, username, display_name, timezone, channel_preference, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateRecipientParams struct {
	ID                string
	Username          string
	DisplayName       string
	Timezone          string
	ChannelPreference string
	CreatedAt         string
}

func (q *Queries) CreateRecipient(ctx context.Context, arg CreateRecipientParams) error {
	_, err := q.db.ExecContext(ctx, createRecipient,
		arg.ID,
		arg.Username,
		arg.DisplayName,
		arg.Timezone,
		arg.ChannelPreference,
		arg.CreatedAt,
	)
	return err
}

const deleteRecipient = `-- name: DeleteRecipient :execrows
DELETE FROM recipients WHERE username = ?
`

func (q *Queries) DeleteRecipient(ctx context.Context, username string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRecipient, username)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getRecipientByID = `-- name: GetRecipientByID :one
SELECT id, username, display_name, timezone, channel_preference, created_at FROM recipients WHERE id = ?
`

func (q *Queries) GetRecipientByID(ctx context.Context, id string) (Recipient, error) {
	row := q.db.QueryRowContext(ctx, getRecipientByID, id)
	var i Recipient
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Timezone,
		&i.ChannelPreference,
		&i.CreatedAt,
	)
	return i, err
}

const getRecipientByUsername = `-- name: GetRecipientByUsername :one
SELECT id, username, display_name, timezone, channel_preference, created_at FROM recipients WHERE username = ?
`

func (q *Queries) GetRecipientByUsername(ctx context.Context, username string) (Recipient, error) {
	row := q.db.QueryRowContext(ctx, getRecipientByUsername, username)
	var i Recipient
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Timezone,
		&i.ChannelPreference,
		&i.CreatedAt,
	)
	return i, err
}

const getRecipientsByUsernames = `-- name: GetRecipientsByUsernames :many
SELECT id, username, display_name, timezone, channel_preference, created_at FROM recipients WHERE username IN (/*SLICE:usernames*/?) ORDER BY username
`

func (q *Queries) GetRecipientsByUsernames(ctx context.Context, usernames []string) ([]Recipient, error) {
	query := getRecipientsByUsernames
	var queryParams []interface{}
	if len(usernames) > 0 {
		for _, v := range usernames {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:usernames*/?", strings.Repeat(",?", len(usernames))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:usernames*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recipient{}
	for rows.Next() {
		var i Recipient
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Timezone,
			&i.ChannelPreference,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipients = `-- name: ListRecipients :many
SELECT id, username, display_name, timezone, channel_preference, created_at FROM recipients ORDER BY username
`

func (q *Queries) ListRecipients(ctx context.Context) ([]Recipient, error) {
	rows, err := q.db.QueryContext(ctx, listRecipients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recipient{}
	for rows.Next() {
		var i Recipient
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Timezone,
			&i.ChannelPreference,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecipient = `-- name: UpdateRecipient :execrows
UPDATE recipients SET display_name = ?, timezone = ?, channel_preference = ? WHERE username = ?
`

type UpdateRecipientParams struct {
	DisplayName       string
	Timezone          string
	ChannelPreference string
	Username          string
}

func (q *Queries) UpdateRecipient(ctx context.Context, arg UpdateRecipientParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateRecipient,
		arg.DisplayName,
		arg.Timezone,
		arg.ChannelPreference,
		arg.Username,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
